module.exports = Object.freeze({
  // MODAL_BODY_TYPES: {
  //   USER_DETAIL: "USER_DETAIL",
  //   LEAD_ADD_NEW: "LEAD_ADD_NEW",
  //   CONFIRMATION: "CONFIRMATION",
  //   DEFAULT: "",
  // },
  MODAL_BODY_TYPES: {
    CONFIRMATION: "CONFIRMATION_MODAL",
    EDIT_PEOPLE: "EDIT_PEOPLE",
    ADD_EDIT_CATEGORY: "ADD_EDIT_CATEGORY_MODAL",
    ADD_EDIT_SUB_CATEGORY: "ADD_EDIT_SUB_CATEGORY_MODAL",
    EXCEL_PREVIEW: "EXCEL_PREVIEW_MODAL",
    GENERATE_REPORT: "GENERATE_REPORT_MODAL",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
  },
});
